In [1]:
import numpy as np

## array creation

In [2]:
a=np.array([1,2,3,4,6])
print(a)

[1 2 3 4 6]


## Array manipulation (Basic Operations upon the elements of the array) 
sum, max, min, mean(avg)

In [3]:
sum=np.sum(a)
Avg=np.mean(a)
maximum=np.max(a)
minimum=np.min(a)
print(sum)
print(Avg)
print(maximum)
print(minimum)

16
3.2
6
1


## Operations among two arrays
add, subtract, multiply, divide


In [8]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6,])
print("element wise sum:",np.add(arr1,arr2))
print("element wise substraction:",np.subtract(arr1,arr2))
print("element wise multiplication:", np.multiply(arr1,arr2))
print("elemet wise divide:", np.divide(arr1,arr2))

element wise sum: [5 7 9]
element wise substraction: [-3 -3 -3]
element wise multiplication: [ 4 10 18]
elemet wise divide: [0.25 0.4  0.5 ]


## Statistical Operations
median, variance, standard deviation, percentile


In [9]:
arr3=np.array([1,3,5])
print("Median:",np.median(arr3))
print("variance:",np.var(arr3))
print("standard deviation:", np.std(arr3))
print("percentile(50th):",np.percentile(arr3,50))

Median: 3.0
variance: 2.6666666666666665
standard deviation: 1.632993161855452
percentile(50th): 3.0


## Linear Algebra
matrix multiplication, determinant of a matrix, inverse of a matrix

In [17]:
mat1=np.array([[1,2],[2,3]])
mat2=np.array([[3,4],[4,5]])


# matrix multiplication
mm=np.dot(mat1,mat2)
print("Matrix Multiplication:")
print(mm)

# determinant
d1=np.linalg.det(mat1)
d2=np.linalg.det(mat2)

print("Determinants of the two matrices:")
print(d1)
print(d2)

# inverse
inverse= np.linalg.inv(mat2)
print("Inverse of matrix 2:")
print(inverse)

Matrix Multiplication:
[[11 14]
 [18 23]]
Determinants of the two matrices:
-1.0
-1.0
Inverse of matrix 2:
[[-5.  4.]
 [ 4. -3.]]
